"""Add timestamps and optimization indexes

Revision ID: 41a8f656bad0
Revises: 04a736e9596d
Create Date: 2026-04-20 14:45:30.614821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a8f656bad0'
down_revision: Union[str, Sequence[str], None] = '04a736e9596d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_credentials', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('broker_credentials', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_broker_credentials_broker_name'), 'broker_credentials', ['broker_name'], unique=False)
    op.create_index(op.f('ix_broker_credentials_is_active'), 'broker_credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_broker_credentials_user_id'), 'broker_credentials', ['user_id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_mobile_no'), 'users', ['mobile_no'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_no'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_broker_credentials_user_id'), table_name='broker_credentials')
    op.drop_index(op.f('ix_broker_credentials_is_active'), table_name='broker_credentials')
    op.drop_index(op.f('ix_broker_credentials_broker_name'), table_name='broker_credentials')
    op.drop_column('broker_credentials', 'updated_at')
    op.drop_column('broker_credentials', 'created_at')
    # ### end Alembic commands ###
